package com.situ.ow.mapper;

import com.situ.ow.pojo.Carousel;
import com.situ.ow.pojo.CarouselExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int countByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int deleteByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int insertSelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    List<Carousel> selectByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    Carousel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int updateByExample(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 13:49:55 CST 2017
     */
    int updateByPrimaryKey(Carousel record);
}