package com.situ.ow.mapper;

import com.situ.ow.pojo.Carousel;
import com.situ.ow.pojo.CarouselExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    long countByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    int deleteByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    int insertSelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    List<Carousel> selectByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    int updateByExample(@Param("record") Carousel record, @Param("example") CarouselExample example);
}