package com.situ.ow.pojo;

import java.io.Serializable;
import java.util.Date;

public class Carousel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.id
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.type
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.text_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String textInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.img_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String imgInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.url_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String urlInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.index_num
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private Integer indexNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.level_num
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String levelNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.text_format
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String textFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.version
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.status
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.update_userID
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private String updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_setting_carousel.update_time
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.id
     *
     * @return the value of tbl_setting_carousel.id
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.id
     *
     * @param id the value for tbl_setting_carousel.id
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.type
     *
     * @return the value of tbl_setting_carousel.type
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.type
     *
     * @param type the value for tbl_setting_carousel.type
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.text_info
     *
     * @return the value of tbl_setting_carousel.text_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getTextInfo() {
        return textInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.text_info
     *
     * @param textInfo the value for tbl_setting_carousel.text_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setTextInfo(String textInfo) {
        this.textInfo = textInfo == null ? null : textInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.img_info
     *
     * @return the value of tbl_setting_carousel.img_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getImgInfo() {
        return imgInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.img_info
     *
     * @param imgInfo the value for tbl_setting_carousel.img_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setImgInfo(String imgInfo) {
        this.imgInfo = imgInfo == null ? null : imgInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.url_info
     *
     * @return the value of tbl_setting_carousel.url_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getUrlInfo() {
        return urlInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.url_info
     *
     * @param urlInfo the value for tbl_setting_carousel.url_info
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setUrlInfo(String urlInfo) {
        this.urlInfo = urlInfo == null ? null : urlInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.index_num
     *
     * @return the value of tbl_setting_carousel.index_num
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public Integer getIndexNum() {
        return indexNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.index_num
     *
     * @param indexNum the value for tbl_setting_carousel.index_num
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setIndexNum(Integer indexNum) {
        this.indexNum = indexNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.level_num
     *
     * @return the value of tbl_setting_carousel.level_num
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getLevelNum() {
        return levelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.level_num
     *
     * @param levelNum the value for tbl_setting_carousel.level_num
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setLevelNum(String levelNum) {
        this.levelNum = levelNum == null ? null : levelNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.text_format
     *
     * @return the value of tbl_setting_carousel.text_format
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getTextFormat() {
        return textFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.text_format
     *
     * @param textFormat the value for tbl_setting_carousel.text_format
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setTextFormat(String textFormat) {
        this.textFormat = textFormat == null ? null : textFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.version
     *
     * @return the value of tbl_setting_carousel.version
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.version
     *
     * @param version the value for tbl_setting_carousel.version
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.status
     *
     * @return the value of tbl_setting_carousel.status
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.status
     *
     * @param status the value for tbl_setting_carousel.status
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.update_userID
     *
     * @return the value of tbl_setting_carousel.update_userID
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public String getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.update_userID
     *
     * @param updateUserid the value for tbl_setting_carousel.update_userID
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setUpdateUserid(String updateUserid) {
        this.updateUserid = updateUserid == null ? null : updateUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_setting_carousel.update_time
     *
     * @return the value of tbl_setting_carousel.update_time
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_setting_carousel.update_time
     *
     * @param updateTime the value for tbl_setting_carousel.update_time
     *
     * @mbg.generated Tue Nov 20 21:19:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}