package com.situ.ow.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarouselExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public CarouselExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTextInfoIsNull() {
            addCriterion("text_info is null");
            return (Criteria) this;
        }

        public Criteria andTextInfoIsNotNull() {
            addCriterion("text_info is not null");
            return (Criteria) this;
        }

        public Criteria andTextInfoEqualTo(String value) {
            addCriterion("text_info =", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoNotEqualTo(String value) {
            addCriterion("text_info <>", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoGreaterThan(String value) {
            addCriterion("text_info >", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoGreaterThanOrEqualTo(String value) {
            addCriterion("text_info >=", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoLessThan(String value) {
            addCriterion("text_info <", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoLessThanOrEqualTo(String value) {
            addCriterion("text_info <=", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoLike(String value) {
            addCriterion("text_info like", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoNotLike(String value) {
            addCriterion("text_info not like", value, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoIn(List<String> values) {
            addCriterion("text_info in", values, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoNotIn(List<String> values) {
            addCriterion("text_info not in", values, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoBetween(String value1, String value2) {
            addCriterion("text_info between", value1, value2, "textInfo");
            return (Criteria) this;
        }

        public Criteria andTextInfoNotBetween(String value1, String value2) {
            addCriterion("text_info not between", value1, value2, "textInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoIsNull() {
            addCriterion("img_info is null");
            return (Criteria) this;
        }

        public Criteria andImgInfoIsNotNull() {
            addCriterion("img_info is not null");
            return (Criteria) this;
        }

        public Criteria andImgInfoEqualTo(String value) {
            addCriterion("img_info =", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoNotEqualTo(String value) {
            addCriterion("img_info <>", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoGreaterThan(String value) {
            addCriterion("img_info >", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoGreaterThanOrEqualTo(String value) {
            addCriterion("img_info >=", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoLessThan(String value) {
            addCriterion("img_info <", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoLessThanOrEqualTo(String value) {
            addCriterion("img_info <=", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoLike(String value) {
            addCriterion("img_info like", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoNotLike(String value) {
            addCriterion("img_info not like", value, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoIn(List<String> values) {
            addCriterion("img_info in", values, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoNotIn(List<String> values) {
            addCriterion("img_info not in", values, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoBetween(String value1, String value2) {
            addCriterion("img_info between", value1, value2, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andImgInfoNotBetween(String value1, String value2) {
            addCriterion("img_info not between", value1, value2, "imgInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoIsNull() {
            addCriterion("url_info is null");
            return (Criteria) this;
        }

        public Criteria andUrlInfoIsNotNull() {
            addCriterion("url_info is not null");
            return (Criteria) this;
        }

        public Criteria andUrlInfoEqualTo(String value) {
            addCriterion("url_info =", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoNotEqualTo(String value) {
            addCriterion("url_info <>", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoGreaterThan(String value) {
            addCriterion("url_info >", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoGreaterThanOrEqualTo(String value) {
            addCriterion("url_info >=", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoLessThan(String value) {
            addCriterion("url_info <", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoLessThanOrEqualTo(String value) {
            addCriterion("url_info <=", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoLike(String value) {
            addCriterion("url_info like", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoNotLike(String value) {
            addCriterion("url_info not like", value, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoIn(List<String> values) {
            addCriterion("url_info in", values, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoNotIn(List<String> values) {
            addCriterion("url_info not in", values, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoBetween(String value1, String value2) {
            addCriterion("url_info between", value1, value2, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andUrlInfoNotBetween(String value1, String value2) {
            addCriterion("url_info not between", value1, value2, "urlInfo");
            return (Criteria) this;
        }

        public Criteria andIndexNumIsNull() {
            addCriterion("index_num is null");
            return (Criteria) this;
        }

        public Criteria andIndexNumIsNotNull() {
            addCriterion("index_num is not null");
            return (Criteria) this;
        }

        public Criteria andIndexNumEqualTo(Integer value) {
            addCriterion("index_num =", value, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumNotEqualTo(Integer value) {
            addCriterion("index_num <>", value, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumGreaterThan(Integer value) {
            addCriterion("index_num >", value, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("index_num >=", value, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumLessThan(Integer value) {
            addCriterion("index_num <", value, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumLessThanOrEqualTo(Integer value) {
            addCriterion("index_num <=", value, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumIn(List<Integer> values) {
            addCriterion("index_num in", values, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumNotIn(List<Integer> values) {
            addCriterion("index_num not in", values, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumBetween(Integer value1, Integer value2) {
            addCriterion("index_num between", value1, value2, "indexNum");
            return (Criteria) this;
        }

        public Criteria andIndexNumNotBetween(Integer value1, Integer value2) {
            addCriterion("index_num not between", value1, value2, "indexNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumIsNull() {
            addCriterion("level_num is null");
            return (Criteria) this;
        }

        public Criteria andLevelNumIsNotNull() {
            addCriterion("level_num is not null");
            return (Criteria) this;
        }

        public Criteria andLevelNumEqualTo(String value) {
            addCriterion("level_num =", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumNotEqualTo(String value) {
            addCriterion("level_num <>", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumGreaterThan(String value) {
            addCriterion("level_num >", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumGreaterThanOrEqualTo(String value) {
            addCriterion("level_num >=", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumLessThan(String value) {
            addCriterion("level_num <", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumLessThanOrEqualTo(String value) {
            addCriterion("level_num <=", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumLike(String value) {
            addCriterion("level_num like", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumNotLike(String value) {
            addCriterion("level_num not like", value, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumIn(List<String> values) {
            addCriterion("level_num in", values, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumNotIn(List<String> values) {
            addCriterion("level_num not in", values, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumBetween(String value1, String value2) {
            addCriterion("level_num between", value1, value2, "levelNum");
            return (Criteria) this;
        }

        public Criteria andLevelNumNotBetween(String value1, String value2) {
            addCriterion("level_num not between", value1, value2, "levelNum");
            return (Criteria) this;
        }

        public Criteria andTextFormatIsNull() {
            addCriterion("text_format is null");
            return (Criteria) this;
        }

        public Criteria andTextFormatIsNotNull() {
            addCriterion("text_format is not null");
            return (Criteria) this;
        }

        public Criteria andTextFormatEqualTo(String value) {
            addCriterion("text_format =", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatNotEqualTo(String value) {
            addCriterion("text_format <>", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatGreaterThan(String value) {
            addCriterion("text_format >", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatGreaterThanOrEqualTo(String value) {
            addCriterion("text_format >=", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatLessThan(String value) {
            addCriterion("text_format <", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatLessThanOrEqualTo(String value) {
            addCriterion("text_format <=", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatLike(String value) {
            addCriterion("text_format like", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatNotLike(String value) {
            addCriterion("text_format not like", value, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatIn(List<String> values) {
            addCriterion("text_format in", values, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatNotIn(List<String> values) {
            addCriterion("text_format not in", values, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatBetween(String value1, String value2) {
            addCriterion("text_format between", value1, value2, "textFormat");
            return (Criteria) this;
        }

        public Criteria andTextFormatNotBetween(String value1, String value2) {
            addCriterion("text_format not between", value1, value2, "textFormat");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIsNull() {
            addCriterion("update_userID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIsNotNull() {
            addCriterion("update_userID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridEqualTo(String value) {
            addCriterion("update_userID =", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotEqualTo(String value) {
            addCriterion("update_userID <>", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridGreaterThan(String value) {
            addCriterion("update_userID >", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridGreaterThanOrEqualTo(String value) {
            addCriterion("update_userID >=", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLessThan(String value) {
            addCriterion("update_userID <", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLessThanOrEqualTo(String value) {
            addCriterion("update_userID <=", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridLike(String value) {
            addCriterion("update_userID like", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotLike(String value) {
            addCriterion("update_userID not like", value, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridIn(List<String> values) {
            addCriterion("update_userID in", values, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotIn(List<String> values) {
            addCriterion("update_userID not in", values, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridBetween(String value1, String value2) {
            addCriterion("update_userID between", value1, value2, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateUseridNotBetween(String value1, String value2) {
            addCriterion("update_userID not between", value1, value2, "updateUserid");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 27 15:36:48 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_setting_carousel
     *
     * @mbg.generated Tue Nov 27 15:36:48 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}